### ISSUE TITLE
bug kosa kata

### ISSUE THREAD

**Issue by ifanzalukhu97** [ikhsanalatsary/akarata#11]
- santai = **santa**
- strategi = **strateg**
- direkomendasikan = **rekomendas**
- pelayannya = **lay**
- kekinian = **kin**
- mengecewakan = **ecewa**
-lokasi = **lokas**

**Comment by ikhsanalatsary** [comment]
@ifanzalukhu97 masalah ini sudah diperbaiki dan bisa mencobanya di https://akarata.netlify.com/
namun pustakanya belum dipublikasi ke `npm` maupun `unpkg`. Untuk masalah kata `rekomendasi` ini hampir benar. masih bermasalah jika ada imbuhan diawal dan diakhir seperti `direkomendasikan` tapi jika hanya awalan saja seperti `direkomendasi` maka hasilnya `rekomendasi`. Saya tutup saja tiket ini, dan akan buat tiket baru untuk masalah `rekomendasi`.
