### ISSUE TITLE
can not use in angular typescript

### ISSUE THREAD

**Issue by s-triar** [ikhsanalatsary/akarata#3]
hi. i want to use akara to my app but it could not load. the error is
`error TS7016: Could not find a declaration file for module 'akarata'. 'D:/MyProject/stkiNew/node_modules/akarata/dist/index.js' implicitly has an 'any' type.
  Try npm install @types/akarata if it exists or add a new declaration (.d.ts) file containing declare module 'akarata';`

**Comment by ikhsanalatsary** [comment]
Yup, this lib is not binding with typescript. cause this repo created before TS hyped😁
