### ISSUE TITLE
peleburan kata

### ISSUE THREAD

**Issue by harissucipto** [ikhsanalatsary/akarata#4]
terdapat masalah ketika melakuakan stemming pada kata "mengatakan" yang hasilnya menjadi ata, dimana harusnya menjadi kata, karena adanya peleburan kata  http://penalispuspa.blogspot.co.id/2014/09/imbuhan-me-bertemu-kata-dasar-k-t-s-p.html

**Comment by ikhsanalatsary** [comment]
Makasih laporannya. Ya repo ini udah lama terbengkalai Dan mesti di - update semua. Jika ada kesempatan akan diperbaiki. Dan pull request juga welcome apabila menemukan solusi. 😊

**Comment by ikhsanalatsary** [comment]
@harissucipto masalah ini sudah diperbaiki dan bisa mencobanya di https://akarata.netlify.com/
namun pustakanya belum dipublikasi ke`npm` atau pun `unpkg`.
