### ISSUE TITLE
Dokumentasi bahasa inggris

### ISSUE THREAD

**Issue by ikhsanalatsary** [ikhsanalatsary/akarata#7]
Readme yang ada sekarang masih terbatas bahasa Indonesia. Sangat bagus apabila ada readme versi bahasa Inggris, guna bagi orang yang bukan asli Indonesia yang ingin mencoba pustaka ini. Penamaan filenya Mungkin `Readme.eng.md` Atau `Readme.english.md` Atau ada yang mau kasih masukan?

**Comment by sukmaragil** [comment]
I'll help this one too

**Comment by ikhsanalatsary** [comment]
good @sukmaragil & @adamfdl 👍
